"""add_draft_content

Revision ID: d986277a770b
Revises: 1cec23cb67da
Create Date: 2026-07-23 14:17:53.168758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd986277a770b'
down_revision: Union[str, None] = '1cec23cb67da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('draft_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'draft_content')
    # ### end Alembic commands ###
